Configure tm bot to run infrastructure integration test
gardener/gardener-extension-provider-alicloud pull request #140
Opened 2020-08-31 14:59 UTC by schrodit

**How to categorize this PR?**

/kind test
/priority normal
/platform alicloud

**What this PR does / why we need it**:

Configures the testmachinery bot to run infrastructure integration test.
prerequisite for https://github.com/gardener/gardener-extension-provider-alicloud/pull/140

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

2020-08-31 15:00 UTC, rfranzke approved these changes
/lgtm

2020-09-01 03:08 UTC, jia-jerry requested changes
@schrodit , Can we feed VPC-ID to the test run just like our e2e test. This VPC is attached with a pre-created NATGateway and it is shared with all testing shoots. The background is below. On AliCloud, NAT Gateway is charged daily and it is around 2 euros. Though AliCloud provided a beta version of NATGateway, which is charged hourly, but the API is different and we can't consume it so far.

@EmoinLanyu

2020-09-01 06:03 UTC, schrodit commented
@jia-jerry the test are executed in the same testmachinery cluster as the other tests. 
So it is possible, but I guess the mutating webhook has to be adjusted? cc @EmoinLanyu

2020-09-01 06:15 UTC, EmoinLanyu commented
> @jia-jerry the test are executed in the same testmachinery cluster as the other tests.
> So it is possible, but I guess the mutating webhook has to be adjusted? cc @EmoinLanyu

Hi @schrodit , mutating webhook will only mutate create-shoot Testruns, so this testrun will not be influenced, thus we don't need to adjust the webhook.

2020-09-01 06:16 UTC, minchaow requested changes

2020-09-01 06:16 UTC, minchaow commented on .ci/.testruns/default.yaml
> +  - name: SECRET_ACCESS_KEY
i think it should be `ACCESS_KEY_SECRET`

2020-09-01 06:23 UTC, schrodit commented
@EmoinLanyu adding another env var for the VPC would be also possible.
But I thought that you also might want to add a subnet range so that this test does not interfere with the create shoot test?

I would also prefer to have it explicit in the testrun, if the ip ranges are no problem.

2020-09-01 06:49 UTC, EmoinLanyu commented
@schrodit We planned 31 subnets (total 32 subnets) in the VPC for testing, and 1 is left untouched. We can use the remaining subnet so that we don't interrupt other tests.

2020-09-01 07:35 UTC, ialidzhikov commented
> @schrodit , Can we feed VPC-ID to the test run just like our e2e test? This VPC is attached with a pre-created NATGateway and it is shared with all testing shoots. The background is below. On AliCloud, NAT Gateway is charged daily and it is around 2 euros. Though AliCloud provided a beta version of NATGateway, which is charged hourly, but the API is different and we can't consume it so far.

What is the reason to do not create the natGateway as part of the test?

2020-09-01 08:01 UTC, schrodit commented
> What is the reason to do not create the natGateway as part of the test?

The reasons are the costs of nat gateways in Alicloud. They are charged by day not minute or hour which had a massive affect on costs for alicloud.

But maybe this test is not affected as we do not run this testcase very often as we do with the default tests? 
@jia-jerry WDYT?

2020-09-01 08:12 UTC, jia-jerry commented
> > What is the reason to do not create the natGateway as part of the test?
> 
> The reasons are the costs of nat gateways in Alicloud. They are charged by day not minute or hour which had a massive affect on costs for alicloud.
> 
> But maybe this test is not affected as we do not run this testcase very often as we do with the default tests?
> @jia-jerry WDYT?

Ideally, we should also cover NAT Gateway  creation. I'm thinking the mechanism of infra-test triggering. Can we trigger the test with condition such as `main.tf` is changed in the PR?

2020-09-01 08:15 UTC, schrodit commented
> Ideally, we should also cover NAT Gateway creation. I'm thinking the mechanism of infra-test triggering. Can we trigger the test with condition such as main.tf is changed in the PR?

Currently this test is only triggered manually. So the maintainers decide when to trigger the test.

2020-09-01 08:34 UTC, jia-jerry commented
> > Ideally, we should also cover NAT Gateway creation. I'm thinking the mechanism of infra-test triggering. Can we trigger the test with condition such as main.tf is changed in the PR?
> 
> Currently this test is only triggered manually. So the maintainers decide when to trigger the test.

@minchaow  has already covered the 2 cases, creating NATGateway and reusing NATGateway. @schrodit, for reusing NATGateway case, I would like to use an existing VPC which e2e is using because it will save money :). So would you help configure VPC_ID env ?

2020-09-01 15:14 UTC, jia-jerry approved these changes

2020-09-02 02:31 UTC, minchaow commented
/lgtm

2020-09-02 02:32 UTC, minchaow approved these changes

2020-09-02 02:33 UTC, merged