check whether the imageId is public
gardener/gardener-extension-provider-alicloud pull request #153
Opened 2020-09-15 11:43 UTC by knightXun

If users choose alicloud public os image, the infrastructure controller will hung there.

2020-09-15 12:48 UTC, jia-jerry requested changes

2020-09-15 12:48 UTC, jia-jerry commented on pkg/alicloud/client/client.go
> +	response, err := c.client.DescribeImages(request)
You need to handle pages

2020-09-15 12:48 UTC, jia-jerry commented on pkg/alicloud/client/client.go
> +func (c *ecsClient) CheckIfImagePublic(ctx context.Context, imageID string) (bool, error) {
Please enhance CheckIfImageExists method directly. Please check it also works for custom shared image

2020-09-15 12:53 UTC, jia-jerry commented
It seems that AliCloud API has a bug. I would suggest you urge AliCloud to fix their API.

2020-09-16 10:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/gardener-extension-provider-alicloud?pullRequest=153) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/gardener-extension-provider-alicloud?pullRequest=153) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/gardener-extension-provider-alicloud?pullRequest=153) it.</sub>

2020-09-18 06:13 UTC, rfranzke commented
/status author-action

2020-09-21 02:16 UTC, closed without merging