Csi ccm upgrade
gardener/gardener-extension-provider-alicloud pull request #272
Opened 2021-04-20 08:11 UTC by minchaow

**How to categorize this PR?**

/area open-source
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:
This PR is to upgrade the version of Alicloud CCM and CSI-plugin.
**Which issue(s) this PR fixes**:
Fixes #
None
**Special notes for your reviewer**:

**Release note**:

```other user
The alibaba-cloud-controller-manager is upgraded to version v1.9.3.372-gcf3535b-aliyun
The csi-plugin-alicloud is upgraded to version v1.18.8.45-1c5d2cd1-aliyun
```

2021-04-20 08:12 UTC, minchaow commented
/assign @jia-jerry

2021-04-20 10:03 UTC, vpnachev submitted a review, later dismissed

2021-04-20 10:03 UTC, vpnachev commented on charts/images.yaml
> +  tag: v1.9.3.372 # the upstream image is using non-semver tag (registry.cn-shanghai.aliyuncs.com/acs/cloud-controller-manager-amd64:v1.9.3.372-gcf3535b-aliyun).
```suggestion
  tag: v1.9.3-372 # the upstream image is using non-semver tag (registry.cn-shanghai.aliyuncs.com/acs/cloud-controller-manager-amd64:v1.9.3.372-gcf3535b-aliyun).
```

2021-04-20 11:59 UTC, vpnachev reviewed
/lgtm code wise

2021-04-21 05:50 UTC, jia-jerry requested changes

2021-04-21 05:50 UTC, jia-jerry commented on charts/images.yaml
>    sourceRepository: https://github.com/AliyunContainerService/csi-plugin
```suggestion
  sourceRepository: https://github.com/kubernetes-sigs/alibaba-cloud-csi-driver
```

2021-04-21 06:03 UTC, jia-jerry approved these changes

2021-04-21 07:09 UTC, merged