add tags from pool to machine class
gardener/gardener-extension-provider-alicloud pull request #374
Opened 2021-10-26 08:41 UTC by shaoyongfeng

**How to categorize this PR?**
/area control-plane
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:
Labels from work pool is not added to ECS instance. In this PR, we add these labels to machineclass so that they will be added to ECS as tag
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other user
Copy labels from work pool to ECS instance Tags.
```

2021-11-21 10:17 UTC, jia-jerry requested changes

2021-11-21 10:17 UTC, jia-jerry commented on pkg/controller/worker/machines.go
> +			dataDisk["encrypted"] = true
Please handle encrypted logic in other logic. There will be side effect when a shoot is reconciled.

2021-11-21 10:17 UTC, jia-jerry commented on pkg/controller/common/encryptimage.go
> +		return (v.Encrypted == nil || v.Encrypted != nil && *v.Encrypted), nil
Please handle encrypted logic in other logic. There will be side effect when a shoot is reconciled.

2021-11-21 10:17 UTC, jia-jerry commented on pkg/controller/common/encryptimage.go
> +		return (v.Encrypted == nil || v.Encrypted != nil && *v.Encrypted), nil
Please handle encrypted logic in other logic. There will be side effect when a shoot is reconciled.

2021-11-26 08:47 UTC, jia-jerry approved these changes

2021-11-26 09:02 UTC, EmoinLanyu approved these changes
/lgtm

2021-11-26 09:05 UTC, EmoinLanyu commented
/unhold

2021-11-26 09:22 UTC, merged