Upgrade csi-plugin-alicloud
gardener/gardener-extension-provider-alicloud pull request #429
Opened 2022-02-08 06:39 UTC by ary1992

**How to categorize this PR?**

/area open-source
/kind enhancement
/platform alicloud

**What this PR does / why we need it**:
This PR is to upgrade the version of Alicloud CSI-plugin.
**Which issue(s) this PR fixes**:
None

**Special notes for your reviewer**:

**Release note**:

```other operator
The csi-plugin-alicloud is upgraded to version v1.22.8-e84838c-aliyun
```

2022-02-08 08:39 UTC, jia-jerry requested changes

2022-02-08 08:39 UTC, jia-jerry commented on charts/images.yaml
> +  repository: registry.cn-hangzhou.aliyuncs.com/acs/csi-plugin
```suggestion
  repository: registry.eu-central-1.aliyuncs.com/acs/csi-plugin
```

2022-02-08 08:41 UTC, jia-jerry commented on charts/images.yaml
> +  repository: registry.cn-hangzhou.aliyuncs.com/acs/csi-plugin
We would suggest to use images located other than Mainland China by default. You may use image-overwrite to change images when you deploy it.

2022-02-08 08:55 UTC, EmoinLanyu commented
/hold

2022-02-08 08:55 UTC, EmoinLanyu commented
/test

2022-02-10 04:57 UTC, EmoinLanyu commented
/test

2022-02-10 07:35 UTC, EmoinLanyu commented
Can't seem to find the problems of the tests. But the PR does not affect infra part which the tests are about. I will proceed with merging.

2022-02-10 07:35 UTC, EmoinLanyu commented
/unhold

2022-02-10 07:36 UTC, EmoinLanyu approved these changes
/lgtm

2022-02-10 07:36 UTC, merged